version: "3.7"
services:
  db:
    image: postgres:11-alpine
    env_file: .env
  backend:
    container_name: "backend"
    build:
      context: ./stock-market-game-backend
      dockerfile: Dockerfile.backend
    expose:
       - "8080"
    depends_on:
      - db
  frontend:
    container_name: "frontend"
    build:
      context: ./stock-market-game-frontend
      dockerfile: Dockerfile.prod
    expose:
      - "80"
        #    depends_on:
        #      - backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - frontend
      - backend 
