version: "3.7"
services:
  db:
    image: postgres:11-alpine
    env_file: .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  backend:
    env_file: .env
    container_name: "backend"
    build:
      context: ./stock-market-game-backend
    expose:
      - "8080"
    depends_on:
      - db
  frontend:
    container_name: "frontend"
    build:
      context: ./stock-market-game-frontend
      dockerfile: Dockerfile.prod
    expose:
      - "80"
  rabbitmq:
    build: ./jbs/rabbitmq
    container_name: rabbitmq
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management load_definitions "/tmp/rabbit.definitions.json"
    expose:
      - "5672"
      - "15672"
    restart: on-failure:5
  data_fetcher:
    build: 
      context: ./jbs/data_services
      dockerfile: Dockerfile.df
    container_name: 'data_fetcher'
    env_file: .env
    restart: on-failure:10
    depends_on:
      - rabbitmq
  info_provider:
    build:
      context: ./jbs/data_services
      dockerfile: Dockerfile.ip
    container_name: 'info_provider'
    environment:
      - DEBUG=True
      - INFOPRO_PORT=8050
    restart: on-failure:10
    expose: 
      - "8050"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
#      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend 
  redis:
    image: redis:6.2.6-alpine
    command: redis-server --requirepass
    container_name: redis
    expose:
      - "6379"

  stock_analysis:
    build: 
      context: ./jbs/stock_analysis
      dockerfile: Dockerfile
    container_name: stock_analysis
    env_file: .env
    restart: always
    depends_on:
      - redis
      - rabbitmq